import Header from '@/layout/Header/Header'
import '../styles/main.css';
import Footer from '@/layout/Footer/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className='relative'>
        <Header className="z-20 absolute left-1/2 transform -translate-x-1/2"/>
        <main className='min-h-screen'>
          {children}
        </main>
        <Footer className="z-20 absolute left-1/2 bottom-[0] transform -translate-x-1/2 "/>
      </body>
    </html>
  )
}
